# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

# Disable automatic submodule fetching (it's done recursively)
git:
    submodules: false

# Do a shallow submodule fetch
before_install: git submodule update --init

env:
    global:
        # Make sure beaver is in the PATH
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"
    matrix:
        - DMD='2.071.2-*' DIST=xenial

install: beaver dlang install

script: beaver dlang make

deploy:
    provider: script
    script: beaver bintray upload -d sociomantic-tsunami/dlang/d1to2fix
            build/last/pkg/*.deb
    skip_cleanup: true
    on:
        tags: true
